#!/bin/sh

if [ "latest" = "$DOCKER_TAG" ]; then
    YAMLLINT_VERSION=$(curl https://pypi.org/pypi/yamllint/json -sLo- | grep -Po '"version":"\d+\.\d+\.\d+"' | awk -F'"' '{print $4}')
else
    YAMLLINT_VERSION="$SOURCE_BRANCH"
fi

docker build --build-arg YAMLLINT_VERSION="$YAMLLINT_VERSION" -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
